### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by silasrm** [kmacute/golvalidator#1]
I'm trying this and get a crash.

**Struct and route**
```
type Event struct {
        Name string `json:"event_name" xml:"event_name" form:"event_name" validate:"required|alpha_space"`
        Time string `json:"event_time" xml:"event_time" form:"event_time" validate:"required|min:10|numeric"`
        ActionSource string `json:"action_source" xml:"action_source" form:"action_source"`
        Email string `json:"em" xml:"em" form:"em"`
        Phone string `json:"ph" xml:"ph" form:"ph"`
        Ip string `json:"ip" xml:"ip" form:"ip"`
        OriginIp []string
        Currency string `json:"currency" xml:"currency" form:"currency"`
        Price string `json:"value" xml:"value" form:"value"`
    }

app.Post("/collector", func(c *fiber.Ctx) error {
        c.Accepts("application/json")
        c.AcceptsCharsets("utf-16", "iso-8859-1") 
        // "iso-8859-1"
        c.AcceptsEncodings("compress", "br") 
        // "compress"
        c.AcceptsLanguages("pt", "en") 

        ev := new(Event)

        if err := c.BodyParser(ev); err != nil {
            return err
        }

        errors := golvalidator.ValidateStructs(ev)
        if len(errors) > 0 {
            return c.JSON(fiber.Map{
                "errors": errors,
            })
        }

        // Accept: application/json
        return c.JSON(fiber.Map{
            "ip": c.IP(),
            "ips": c.IPs(),
            "entity": structs.Map(ev),
        })
    })
```

**Request**
`curl -H "Content-Type: application/json" -X POST -d '{}' "http://127.0.0.1:3000/collector"`

**Error**
```
panic: reflect: call of reflect.Value.NumField on ptr Value

goroutine 20 [running]:
reflect.flag.mustBe(...)
        /usr/lib/go-1.16/src/reflect/value.go:221
reflect.Value.NumField(0x7b0ac0, 0xc0003ca000, 0x16, 0xc00012f9b0)
        /usr/lib/go-1.16/src/reflect/value.go:1369 +0xc5
github.com/kmacute/golvalidator.ValidateStructs(0x7b0ac0, 0xc0003ca000, 0xc0003ca000)
        /home/silasrm/go/pkg/mod/github.com/kmacute/golvalidator@v0.0.0-20210528052904-5a0248be89be/ValidateStructs.go:13 +0x125
main.main.func1(0xc0003c8000, 0xc0003a4440, 0xa)
        /arquivos/Sites/vitor/fb-conversion-proxy/main.go:114 +0x235
github.com/gofiber/fiber/v2.(*App).next(0xc00048c000, 0xc0003c8000, 0xc0003c8000, 0xc01d500459, 0x1d50045900000000)
        /home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:126 +0x1ab
github.com/gofiber/fiber/v2.(*App).handler(0xc00048c000, 0xc0003c6000)
        /home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:154 +0x11a
github.com/valyala/fasthttp.(*Server).serveConn(0xc00048e000, 0x8b2198, 0xc00039c018, 0x0, 0x0)
        /home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/server.go:2168 +0x11cc
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc0004d8000, 0xc0003b2020)
        /home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:223 +0xba
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc0004d8000, 0xc0003b2020, 0x7b0000, 0xc0003b2020)
        /home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
        /home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:194 +0x11f
exit status 2
make: *** [Makefile:4: run] Erro 1
```

One question: How to define custom messages errors?

**Comment by kmacute** [comment]
Sorry for the very late reply,

I tried your code.

```
// this doesn't work
ev := new(Event)

// this works
var ev Event
```

I don't know why the dynamic one doesn't work while the proper declaration works on the reflection of golang

for the custom error message, i'll create an update on this, I'm just really busy with my job

**Comment by kmacute** [comment]
got it, you just forgot to put the ampersand before the variable on the bodyParser

![image](https://user-images.githubusercontent.com/48196638/123112738-89e76100-d470-11eb-9552-51649182bd7d.png)

**Comment by silasrm** [comment]
I'll check and test.
Thks!

**Comment by silasrm** [comment]
Hi,

This error continue and I'm lost. 

On reflect documentation (https://pkg.go.dev/reflect#Value.NumField) says: 
```go
func (Value) NumField ¶
func (v Value) NumField() int
NumField returns the number of fields in the struct v. It panics if v's Kind is not Struct.
```

But, this return struct as type:
```go
v := reflect.ValueOf(ev)
reflect.TypeOf(v).Kind()
```

Terminal print: `&{     {[] []   [] [] [] []  [] [] []   []} {   []  }}`

My code with change:

``` go
// Create a new Fiber instance.
app := fiber.New()

// Add middleware.
app.Use(
   logger.New(), // add simple logger
   cors.New(cors.Config{AllowCredentials: true}),
)

app.Post("/collector", func(c *fiber.Ctx) error {
    c.Accepts("application/json")
    c.AcceptsCharsets("utf-16", "iso-8859-1")
    // "iso-8859-1"
    c.AcceptsEncodings("compress", "br")
    // "compress"
    c.AcceptsLanguages("pt", "en")

    ev := new(core.EventData)
    core.LogMessage(fmt.Sprintf("Body: %s", string(c.Request().Body())), fileRequest)
    if err := c.BodyParser(&ev); err != nil {
	return err
    }

    errors := golvalidator.ValidateStructs(ev)
    if len(errors) > 0 {
		  return c.JSON(fiber.Map{
		      "errors": errors,
		  })
}
        // ....
})
```

```
panic: reflect: call of reflect.Value.NumField on ptr Value

goroutine 35 [running]:
reflect.flag.mustBe(...)
	/usr/lib/go-1.16/src/reflect/value.go:221
reflect.Value.NumField(0x98a160, 0xc0000b4400, 0x16, 0xc00036b0f8)
	/usr/lib/go-1.16/src/reflect/value.go:1369 +0xc5
github.com/kmacute/golvalidator.ValidateStructs(0x98a160, 0xc0000b4400, 0xc0000a4060)
	/home/silasrm/go/pkg/mod/github.com/kmacute/golvalidator@v0.0.0-20210528052904-5a0248be89be/ValidateStructs.go:13 +0x125
main.main.func1(0xc0000fe000, 0x0, 0x0)
	/home/silasrm/Sites/quantifique/api-go/api/main.go:102 +0x3a7
github.com/gofiber/fiber/v2.(*App).next(0xc00038ea00, 0xc0000fe000, 0xc0000a7068, 0x4, 0x8)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:126 +0x1ab
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0000fe000, 0xa4093f, 0x20)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/ctx.go:637 +0x88
github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc0000fe000, 0x497ac6, 0x611d2605)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/middleware/cors/cors.go:141 +0x316
github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0000fe000, 0xded15da9, 0xe05240)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/ctx.go:634 +0x59
github.com/gofiber/fiber/v2/middleware/logger.New.func2(0xc0000fe000, 0xc0000a7050, 0xa)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/middleware/logger/logger.go:154 +0x131
github.com/gofiber/fiber/v2.(*App).next(0xc00038ea00, 0xc0000fe000, 0xc0000fe000, 0xc002961039, 0x296103900000000)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:126 +0x1ab
github.com/gofiber/fiber/v2.(*App).handler(0xc00038ea00, 0xc0000fc000)
	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:154 +0x11a
github.com/valyala/fasthttp.(*Server).serveConn(0xc00012cb40, 0xad58e0, 0xc0000a4058, 0x0, 0x0)
	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/server.go:2168 +0x11cc
github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000383e00, 0xc0000ba740)
	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:223 +0xba
github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000383e00, 0xc0000ba740, 0x98ef20, 0xc0000ba740)
	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:195 +0x35
created by github.com/valyala/fasthttp.(*workerPool).getCh
	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:194 +0x11f
exit status 2
make: *** [Makefile:2: run] Erro 1
```

**Comment by silasrm** [comment]
> Hi,
> 
> This error continue and I'm lost.
> 
> On reflect documentation (https://pkg.go.dev/reflect#Value.NumField) says:
> 
> ```go
> func (Value) NumField ¶
> func (v Value) NumField() int
> NumField returns the number of fields in the struct v. It panics if v's Kind is not Struct.
> ```
> 
> But, this return struct as type:
> 
> ```go
> v := reflect.ValueOf(ev)
> reflect.TypeOf(v).Kind()
> ```
> 
> Terminal print: `&{ {[] [] [] [] [] [] [] [] [] []} { [] }}`
> 
> My code with change:
> 
> ```go
> // Create a new Fiber instance.
> app := fiber.New()
> 
> // Add middleware.
> app.Use(
>    logger.New(), // add simple logger
>    cors.New(cors.Config{AllowCredentials: true}),
> )
> 
> app.Post("/collector", func(c *fiber.Ctx) error {
>     c.Accepts("application/json")
>     c.AcceptsCharsets("utf-16", "iso-8859-1")
>     // "iso-8859-1"
>     c.AcceptsEncodings("compress", "br")
>     // "compress"
>     c.AcceptsLanguages("pt", "en")
> 
>     ev := new(core.EventData)
>     core.LogMessage(fmt.Sprintf("Body: %s", string(c.Request().Body())), fileRequest)
>     if err := c.BodyParser(&ev); err != nil {
> 	return err
>     }
> 
>     errors := golvalidator.ValidateStructs(ev)
>     if len(errors) > 0 {
> 		  return c.JSON(fiber.Map{
> 		      "errors": errors,
> 		  })
> }
>         // ....
> })
> ```
> 
> ```
> panic: reflect: call of reflect.Value.NumField on ptr Value
> 
> goroutine 35 [running]:
> reflect.flag.mustBe(...)
> 	/usr/lib/go-1.16/src/reflect/value.go:221
> reflect.Value.NumField(0x98a160, 0xc0000b4400, 0x16, 0xc00036b0f8)
> 	/usr/lib/go-1.16/src/reflect/value.go:1369 +0xc5
> github.com/kmacute/golvalidator.ValidateStructs(0x98a160, 0xc0000b4400, 0xc0000a4060)
> 	/home/silasrm/go/pkg/mod/github.com/kmacute/golvalidator@v0.0.0-20210528052904-5a0248be89be/ValidateStructs.go:13 +0x125
> main.main.func1(0xc0000fe000, 0x0, 0x0)
> 	/home/silasrm/Sites/quantifique/api-go/api/main.go:102 +0x3a7
> github.com/gofiber/fiber/v2.(*App).next(0xc00038ea00, 0xc0000fe000, 0xc0000a7068, 0x4, 0x8)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:126 +0x1ab
> github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0000fe000, 0xa4093f, 0x20)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/ctx.go:637 +0x88
> github.com/gofiber/fiber/v2/middleware/cors.New.func1(0xc0000fe000, 0x497ac6, 0x611d2605)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/middleware/cors/cors.go:141 +0x316
> github.com/gofiber/fiber/v2.(*Ctx).Next(0xc0000fe000, 0xded15da9, 0xe05240)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/ctx.go:634 +0x59
> github.com/gofiber/fiber/v2/middleware/logger.New.func2(0xc0000fe000, 0xc0000a7050, 0xa)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/middleware/logger/logger.go:154 +0x131
> github.com/gofiber/fiber/v2.(*App).next(0xc00038ea00, 0xc0000fe000, 0xc0000fe000, 0xc002961039, 0x296103900000000)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:126 +0x1ab
> github.com/gofiber/fiber/v2.(*App).handler(0xc00038ea00, 0xc0000fc000)
> 	/home/silasrm/go/pkg/mod/github.com/gofiber/fiber/v2@v2.6.0/router.go:154 +0x11a
> github.com/valyala/fasthttp.(*Server).serveConn(0xc00012cb40, 0xad58e0, 0xc0000a4058, 0x0, 0x0)
> 	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/server.go:2168 +0x11cc
> github.com/valyala/fasthttp.(*workerPool).workerFunc(0xc000383e00, 0xc0000ba740)
> 	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:223 +0xba
> github.com/valyala/fasthttp.(*workerPool).getCh.func1(0xc000383e00, 0xc0000ba740, 0x98ef20, 0xc0000ba740)
> 	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:195 +0x35
> created by github.com/valyala/fasthttp.(*workerPool).getCh
> 	/home/silasrm/go/pkg/mod/github.com/valyala/fasthttp@v1.18.0/workerpool.go:194 +0x11f
> exit status 2
> make: *** [Makefile:2: run] Erro 1
> ```

Hi,

I'm change your code here https://github.com/kmacute/golvalidator/blob/main/ValidateStructs.go#L12 to this and error is stopped: `v := reflect.ValueOf(s).Elem()`

Now is ok! https://github.com/silasrm/golvalidator/releases/tag/v0.4.2

![image](https://user-images.githubusercontent.com/197187/129940848-98ab12e9-5e44-42fe-a25b-112fecc065d7.png)
![image](https://user-images.githubusercontent.com/197187/129940899-38029604-e563-45b4-98ff-f63d9db881e0.png)
